repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: observability
    chart: grafana/grafana
    version: 7.3.0
    values:
      - grafana/values.yaml

  - name: kube-prometheus-stack
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    version: 65.4.0
    values:
      - prometheus/values.yaml

